version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
